### ISSUE TITLE
GTK apps' CSD decorations use Breeze icons under Wayland

### ISSUE THREAD

**Issue by openmindead** [paulmcauley/classik#13]
Hi!

>Known issues
>GTK apps' titlebar buttons will not always update if you change a ClassiK setting. Workaround: you need to select another window decoration and then select ClassiK again to generate the GTK titlebar buttons; alternatively you can change your colour scheme and the GTK titlebar buttons will generate.

I'm opening this bug report to comment on a workaround cited above to make you aware of that it works under X11, but in Wayland session CSD buttons are inherited from Breeze despite ClassiK generated ones being in `~/.config/gtk-3.0/assets` folder.

**Comment by paulmcauley** [comment]
Yes, I know. This is a caused by GTK itself: https://bugs.kde.org/show_bug.cgi?id=437082

The GTK developers won't allow the KDE developers to have a way to customise the GTK CSS: https://gitlab.gnome.org/GNOME/gtk/-/issues/3409

**Comment by openmindead** [comment]
Oh, thanks, I remembered why I do not like Gnome so much. That attitude. I read that bug report back in the day, just forgot about it over time.
OK I guess I should close this one since there's nothing you can do about it.
Thank you for this great effort btw. Buttons look very nice.
