### ISSUE TITLE
Ability to disable button gradient

### ISSUE THREAD

**Issue by Akselmo** [paulmcauley/classik#16]
I know this is a nitpicky thing but I am not fan of the new gradient look of the buttons. Would like to be able to make them look "flat" again like in older Breeze.

**Comment by paulmcauley** [comment]
Untick "Translucent backgrounds" under the Buttons tab and you can get back the old look.

**Comment by Akselmo** [comment]
I cant find buttons tab in application styles
![image](https://user-images.githubusercontent.com/13801236/154154815-52ae075d-4629-4835-8882-65346369a664.png)

**Comment by paulmcauley** [comment]
Oh sorry, I thought you were referring to the titlebar buttons in the window decoration. I'm not sure what you mean by the gradient in the buttons. The current application style largely matches that of the current Breeze design.

**Comment by Akselmo** [comment]
In the screenshot, all the buttons and dropdown menus have this very faint gradient. However, I managed to disable it by commenting the following lines out in `kstyle/breezehelper.cpp`

```cpp
        // Gradient
        if (!(flat || down || hovered || checked) && enabled) {
            //QLinearGradient bgGradient(frameRect.topLeft(), frameRect.bottomLeft());
            //bgGradient.setColorAt(0, KColorUtils::mix(bgBrush.color(), Qt::white, 0.03125));
            //bgGradient.setColorAt(0.5, bgBrush.color());
            //bgGradient.setColorAt(1, KColorUtils::mix(bgBrush.color(), Qt::black, 0.03125));
            //QLinearGradient penGradient(frameRect.topLeft(), frameRect.bottomLeft());
            //penGradient.setColorAt(0, KColorUtils::mix(penBrush.color(), Qt::white, 0.03125));
            //penGradient.setColorAt(1, KColorUtils::mix(penBrush.color(), Qt::black, 0.0625));
            //bgBrush = bgGradient;
            //penBrush = penGradient;
        }
``` 

![image](https://user-images.githubusercontent.com/13801236/154246682-b0a576bd-ae74-46a8-961c-f2982b430d6d.png)

Now the buttons are flat as they used to be. 

It is very tiny thing but I prefer the buttons being flat. 😅

**Comment by Akselmo** [comment]
I made a PR: https://github.com/paulmcauley/classik/pull/18

**Comment by paulmcauley** [comment]
Hello, thanks for your PR.

Could you tell me if this in KDE Breeze is the same as what you have done in your PR?:
https://invent.kde.org/plasma/breeze/-/merge_requests/220

If so, then it will eventually end up in ClassiK in some form via Breeze. I think I prefer it with the gradient though.

**Comment by Akselmo** [comment]
Seems like it! 

I do like the gradient now too, funnily enough, which is why I wanted to make an option for them. :)

**Comment by paulmcauley** [comment]
Thank you for this. The equivalent is now implemented on master in https://github.com/paulmcauley/classik/commit/e4a13e87a615ad974779e485cc6fbd63e6448230

**Comment by Akselmo** [comment]
No problem!
