### ISSUE TITLE
Top and bottom margins

### ISSUE THREAD

**Issue by mrmango1** [paulmcauley/classik#24]
Could the top and bottom margin be independent?
![Screenshot_20220504_144553](https://user-images.githubusercontent.com/65833915/166814931-3ced85cf-f9d2-4bb9-8143-b7cb5783a9ea.png)

**Comment by paulmcauley** [comment]
This is now possible with commit 36f76544cd6ce08560405a6acee54f4b8b6a1c03 on master. Toggle the padlock icon to unlocked to allow this to be set independently:
![independent_top_bottom](https://user-images.githubusercontent.com/6924479/178153655-99b4e741-8e7b-4921-90bd-027cf120ad26.png)



 (though why you would want to do this for titlebar top/bottom margins I do not know?)
