### ISSUE TITLE
incomplete type compile error

### ISSUE THREAD

**Issue by paulmcauley** [paulmcauley/classik#27]
Just installed 5.24.90 beta that released yesterday and when compiling I get this error:

```
error: variable ‘std::array<const char*, 1> exceptionClassNames’ has initializer but incomplete type
2749 |             std::array<const char*,1> exceptionClassNames = {"KateScrollBar"};
|                                       ^~~~~~~~~~~~~~~~~~~
```

_Originally posted by @Sojiro84 in https://github.com/paulmcauley/classik/issues/19#issuecomment-1132522419_

**Comment by paulmcauley** [comment]
@Sojiro84 , I cannot reproduce this issue on the 5.24.90 beta on OpenSUSE Leap Argon with GCC v. 7.5.0.

Could you please give details on your distribution, GCC version and whether you are using any custom compiler settings? Are you also trying to compile the latest code from master? The code being referred to is to do with scrollbars and was released with Classsik v3.0 and has nothing to do with the Kornerbug fix.

**Comment by Sojiro84** [comment]
I am on Arch (EndeavourOS). Fully uptodate.

I don't use any custom settings. I download the latest master and then run the install script.

Seems my GCC is version 12.1.0.

I have tried the latest master and the branch called "kornerbug-fix-plasma5.25". Both give the same error.

The log from the master branch is: https://gist.github.com/Sojiro84/51cf9fb2a0ba1fe0a4c0628d1004f057
The log from the "kornerbug-fix-plasma5.25" branch is: https://gist.github.com/Sojiro84/b573c02905ad3084b7fb55c21ab01b54

**Comment by Sojiro84** [comment]
Also tested on my laptop that also has the beta, and I can the same error there.

Downgraded my laptop to 5.24.5 and used the latest official release and compiling that one also shows the Kate scrollbar error.

So strange, since that official release compiled just fine when it was just released.

**Comment by paulmcauley** [comment]
I just updated another OpenSUSE Tumbleweed system and GCC just got updated from 11.2.1 to 12.1.0. I can now reproduce this error, so I'm pretty sure that GCC v. 12.1.0 is the culprit.

I will make a fix...

**Comment by paulmcauley** [comment]
Fix is on master now
