### ISSUE TITLE
Can't Clone The Repository

### ISSUE THREAD

**Issue by adam-adrian** [paulmcauley/classik#30]
When I tried to clone the repo with `git clone https://github.com/paulmcauley/classik`, the cloning progress slowed down when it reaches 12% and after waiting a long time (actually not too long), the progress failed with EOF (if I remember correctly). However, when I download the zip (from the Github page), it downloaded normally.

**Comment by adam-adrian** [comment]
Video:
https://user-images.githubusercontent.com/96514212/172031772-55afe47d-6f73-41f6-b558-1ee8ef696493.mp4

**Comment by adam-adrian** [comment]
https://user-images.githubusercontent.com/96514212/172031794-cec94980-a938-4edf-be1d-5020c9bf63ba.mp4

**Comment by paulmcauley** [comment]
I cannot reproduce this. I just tried and I cloned successfully:
```bash-4.4$ git clone https://github.com/paulmcauley/classik.git
Cloning into 'classik'...
remote: Enumerating objects: 31792, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 31792 (delta 12), reused 21 (delta 11), pack-reused 31761
Receiving objects: 100% (31792/31792), 679.94 MiB | 3.28 MiB/s, done.
Resolving deltas: 100% (21294/21294), done.```

(the reason it's so big is all the various wallpapers and cursors from when it was forked from Breeze)

**Comment by adam-adrian** [comment]
Oh, I understand now. Thank you! I will close this issue.

**Comment by adam-adrian** [comment]
Maybe you want warn the user about this
