### ISSUE TITLE
Feature Request: Add New Type Of Background Shape And Button That Similar To Windows 11 (Or Better)

### ISSUE THREAD

**Issue by adam-adrian** [paulmcauley/classik#32]
(If you want and have a time)
I can't explain so this is a reference image:
![1v8au9etjwe71~2](https://user-images.githubusercontent.com/96514212/173085043-52bd3c3d-54f5-41c7-a7f7-4af22c0eafac.png)
![17p7b5etjwe71~2](https://user-images.githubusercontent.com/96514212/173085215-32995d4f-a8bb-4d5f-bb2d-ed49ae955323.png)

Minimize & Restore button (SVG from willow-theme https://github.com/doncsugar/willow-theme):
![maximize](https://user-images.githubusercontent.com/96514212/173085456-74d80b54-166f-4870-9e7c-255b55194e3e.svg)

![restore](https://user-images.githubusercontent.com/96514212/173085465-a62723f5-f7c4-4df9-8e5c-fee044362ab8.svg)

**Comment by paulmcauley** [comment]
I plan a feature where you can load in any icon from the system icon theme, so you should be able to get Windows-11-style icons that way.

As for the button background shape, Windows 11 currently is the same as "Full-height rectangle" shape with highlight using "background".  Where are the top 2 screenshots from? I may consider adding such a shape, but also have no idea what it would be called!

**Comment by paulmcauley** [comment]
I assume the first 2 images were from here? https://www.reddit.com/r/Windows_Redesign/comments/owa4rk/i_made_a_couple_concept_images_for_title_bar/

**Comment by adam-adrian** [comment]
> I plan a feature where you can load in any icon from the system icon theme, so you should be able to get Windows-11-style icons that way.

Thank you! That's way more better from what I think before.

> I may consider adding such a shape, but also have no idea what it would be called!

Same here, I also don't know

> I assume the first 2 images were from here? https://www.reddit.com/r/Windows_Redesign/comments/owa4rk/i_made_a_couple_concept_images_for_title_bar/

Yes, you're correct

**Comment by adam-adrian** [comment]
> I plan a feature where you can load in any icon from the system icon theme, so you should be able to get Windows-11-style icons that way.

One question: What's the icon name?

And the icons look blurry with medium size other than breeze.

**Comment by paulmcauley** [comment]
> > I plan a feature where you can load in any icon from the system icon theme, so you should be able to get Windows-11-style icons that way.
>  And the icons look blurry with medium size other than breeze.

This is still a work-in-progress. There is an update coming soon to this that should fix that as uses the same scaling as the icons were designed for. It also will tint the icon colour. How the icons will look will also depend on the individual icon theme used. Which theme looks blurry?

**Comment by adam-adrian** [comment]
> If you are talking about "use system icon theme" then there is an update coming soon that will use the same scaling as the icons were designed for. It also will tint the icon colour.

Great! And yes just that is blurry, others is good

**Comment by paulmcauley** [comment]
> > If you are talking about "use system icon theme" then there is an update coming soon that will use the same scaling as the icons were designed for. It also will tint the icon colour.
> 
> Great! And yes just that is blurry, others is good.

The aforementioned update (21e25caa230c7ad47b14125e9652bbab5e2342a2) is now on master. Do you have blurry icons now?

If you get a blurry icon, try a different size. You might also get a blurry icon if you have multiple mixed-DPI monitors on Wayland -- I made a workaround for this for most cases, but it won't be perfect until Qt6 is in Plasma (Plasma 6).

Here is an example of using a quasi-Windows 11 icon theme ("Cobalt") with Classik:
![cobaltIconTheme](https://user-images.githubusercontent.com/6924479/174507265-7c91d2a8-6a60-49ea-aa5c-e0ffec62c21f.png)

**Comment by adam-adrian** [comment]
Thanks, sorry for late reply (i don't receive any notification), I will try it tomorrow.

**Comment by adam-adrian** [comment]
Not too good with medium size:
![Screenshot_20220625_064118](https://user-images.githubusercontent.com/96514212/175749061-f8834708-c5b2-47ea-94c5-2e9103afd5cc.png)
I think I should modify the SVG file.
However, it looks good with 22 pixel(?) size.
Also, I have an idea to let user choose different icon pack, is that possible?

**Comment by paulmcauley** [comment]
Yes, I don't expect size 18 (Medium) to be sharp on LoDPI screens as it isn't really a standard used icon size in icon themes -- I set 16 as the default when you use "Use system icon theme" for that reason. The size 18 (Medium) is just there because that was the default size used for Breeze and the included icons with ClassiK. My screenshot above is with size 22 (device-independent pixels) and seems sharp.

> Also, I have an idea to let user choose different icon pack, is that possible?
I'm not sure what you mean. Could you elaborate? The user can already choose a different icon pack in the Icons section of Appearance settings. Do you mean to include the Icons settings page in classik-settings?

**Comment by adam-adrian** [comment]
I mean, maybe the user want to choose icon from different icon pack, since not all icons pack provide a icon. It can be useful if someone want a Win11 icon for his system, but want use Cobalt for the window decooration icon. But I think this is low-priority since they can modify the icon for themselves.

**Comment by paulmcauley** [comment]
> I mean, maybe the user want to choose window decoration icon from different icon pack, since not all icons pack provide that icon. It can be useful if someone want a Win11 icon for his system, but want use Cobalt for the window decooration icon. 

I understand. This is possible using` void QIcon::setThemeName(const QString &name)`. As for the user interface, I think I could have another drop-down box after you select "System Icon theme" that says "System Icon theme to use for window decorations" with "Current" as the first option, then listing all system icon themes.

However, the problem with allowing the use of two different icon themes at once is that it will lead to some inconsistency as e.g. the icons you get in Plasma when you right-click on a program in the Panel and choose "More" depend on the system icon theme (Cobalt is actually incomplete and doesn't do this properly). GTK4 applications are the same (if you choose "Adwaita as the GNOME/GTK Application Style"  you get the same window-*-symbolic icons from the selected icon theme as I have used). Therefore, this requires more thought so indeed won't be a high priority.
>But I think this is low-priority since they can modify the icon for themselves.
> 
> And people can make a icon pack just for window decoration without any hassle.
You can indeed already do this, though it requires a bit of fiddling by changing the "Inherits=" line in the index.theme to the name of the theme you want to use for the rest of the icons. I designed window-decoration-only icon packs this way (they need updated with a new close button though).

**Comment by adam-adrian** [comment]
> However, the problem with allowing the use of two different icon themes at once is that it will lead to some inconsistency

You're right, i forgot about it. But personally I don't too thinking about that inconsistency, because that's just a little detail that not too important for me.

> You can indeed already do this, though it requires a bit of fiddling by changing the "Inherits=" line in the index.theme to the name of the theme you want to use for the rest of the icons.

I forgot too about this, i will try it soon.

**Comment by adam-adrian** [comment]
And just asking, would you implement this?
![1v8au9etjwe71~2](https://user-images.githubusercontent.com/96514212/173085043-52bd3c3d-54f5-41c7-a7f7-4af22c0eafac.png)
![17p7b5etjwe71~2](https://user-images.githubusercontent.com/96514212/173085215-32995d4f-a8bb-4d5f-bb2d-ed49ae955323.png)

If don't, it's okay, you still do a pretty good job, don't worry 😊

**Comment by paulmcauley** [comment]
> And just asking, would you implement this? ![1v8au9etjwe71~2](https://user-images.githubusercontent.com/96514212/173085043-52bd3c3d-54f5-41c7-a7f7-4af22c0eafac.png) ![17p7b5etjwe71~2](https://user-images.githubusercontent.com/96514212/173085215-32995d4f-a8bb-4d5f-bb2d-ed49ae955323.png)
> 
> If don't, it's okay, you still do a pretty good job, don't worry blush

Yes, in a future version 5 maybe (I will soon release version 4). I would maybe call it "Full-Height Integrated Rounded Rectangle". Detecting which button is at the edge to draw differently will need a bit of work though...

**Comment by paulmcauley** [comment]
> > And just asking, would you implement this? ![1v8au9etjwe71~2](https://user-images.githubusercontent.com/96514212/173085043-52bd3c3d-54f5-41c7-a7f7-4af22c0eafac.png) ![17p7b5etjwe71~2](https://user-images.githubusercontent.com/96514212/173085215-32995d4f-a8bb-4d5f-bb2d-ed49ae955323.png)
> > If don't, it's okay, you still do a pretty good job, don't worry blush
> 
> Yes, in a future version 5 maybe (I will soon release version 4). I would maybe call it "Full-Height Integrated Rounded Rectangle". Detecting which button is at the edge to draw differently will need a bit of work though...

I worked out how to do this, and "Full-height Integrated Rounded Rectangle" is now implemented on master with commit 288a4ecf32016fb8a2330beac3953dee34eaa1e1.

**Comment by paulmcauley** [comment]
This has been now tweaked, and vertical spacing of "Full-height Integrated Rounded Rectangle" now gets adjusted automatically with e8b55c07dbefcd66203f143d5e1c2c015a6f498c .

**Comment by paulmcauley** [comment]
Klassy now has a bundled "Windows 11" preset and "Redmond 11" icons
