### ISSUE TITLE
Opacity Sliders are Disabled

### ISSUE THREAD

**Issue by Arpitpandey992** [paulmcauley/classik#35]
After updating plasme to 5.25, and then installing classik, the opacity sliders are for some reason greyed out.
![image](https://user-images.githubusercontent.com/101496881/174271256-b1ffda2b-d260-41d9-8e5f-c8e2314adb8c.png)

**Comment by paulmcauley** [comment]
This an intentional change. It is because you have manually set opacity in your colour scheme. I thought it was confusing to have opacity set in two places, so to change your opacity in this case you need to edit the colour scheme again.

**Comment by Arpitpandey992** [comment]
> This is an intentional change. It is because you have manually set opacity in your colour scheme. I thought it was confusing to have opacity set in two places, so to change your opacity in this case you need to edit the colour scheme again.

Alright cool. um, How do we change the opacity of a color scheme?

**Comment by paulmcauley** [comment]
The colour schemes are in ~/local/share/color-schemes/
You need to look at the [WM] section or [Colors:Header] / [Colors:Header][Inactive] sections. The opacity is the fourth number in the line.

**Comment by Arpitpandey992** [comment]
> The colour schemes are in ~/local/share/color-schemes/ You need to look at the [WM] section or [Colors:Header] / [Colors:Header][Inactive] sections. The opacity is the fourth number in the line.

Alright Thanks! That works
