### ISSUE TITLE
SetBlur error during compiling

### ISSUE THREAD

**Issue by A944684** [paulmcauley/classik#39]
I have an error during the installation.
I carrefully followed instructions (dependencies, git clone, chmod...)

Manjaro Ruah 21.3.4
KDE plasma 5.24.6
QT 5.15.5
Kernel 5.15.55-1

> [ 16%] Building CXX object kdecoration/CMakeFiles/classikdecoration.dir/breezedecoration.cpp.o
/home/classik/kdecoration/breezedecoration.cpp: Dans la fonction membre « void Breeze::Decoration::updateBlur() »:
/home/xxx/Téléchargements/classik/kdecoration/breezedecoration.cpp:1598:9: erreur: « setBlurRegion » n'a pas été déclaré dans cette portée
 1598 |         setBlurRegion(QRegion());
      |         ^~~~~~~~~~~~~
/home/classik/kdecoration/breezedecoration.cpp:1602:13: erreur: « setBlurRegion » n'a pas été déclaré dans cette portée
 1602 |             setBlurRegion(QRegion(m_windowPath->toFillPolygon().toPolygon()));
      |             ^~~~~~~~~~~~~
/home/classik/kdecoration/breezedecoration.cpp:1604:13: erreur: « setBlurRegion » n'a pas été déclaré dans cette portée
 1604 |             setBlurRegion(QRegion());
      |             ^~~~~~~~~~~~~
make[2]: *** [kdecoration/CMakeFiles/classikdecoration.dir/build.make:138 : kdecoration/CMakeFiles/classikdecoration.dir/breezedecoration.cpp.o] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:512 : kdecoration/CMakeFiles/classikdecoration.dir/all] Erreur 2
make: *** [Makefile:136 : all] Erreur 2

Any idea ?

**Comment by paulmcauley** [comment]
The git master version requires Plasma 5.25.

You can try the older v 3.0 in the releases section.

**Comment by A944684** [comment]
Thank you.
I have another error would you like me to open a new thread ?

home/classik-3.0.breeze5.23.80/kstyle/breezestyle.cpp:2734:39: erreur: la variable « std::array<const char*, 1> exceptionClassNames » a un initialiseur mais a un type incomplet
 2734 |             std::array<const char*,1> exceptionClassNames = {"KateScrollBar"};
      |                                       ^~~~~~~~~~~~~~~~~~~

I guess it is same as #27 ... 
But i can't install from master as you said. 
Do i need to wait my distro update Plasma ?
